development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: interactive_development
  pool: 5
  username: postgres
  password: sharmila
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: interactive_test
  pool: 5
  username: postgres
  password: sharmila
  host: localhost
  port: 5432